name: This is test workflow

on: 
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: Some name to print
        default: World

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo ${{ github.event.inputs.name }}
      - name: Use own Action
        uses: RickardHF/javascript-action@main
  testing:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Say Hello
        run: echo ${{ github.event.inputs.name }}
      - name: Use own Action
        uses: RickardHF/javascript-action@main
  staging:
    needs: [test]
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo ${{ github.event.inputs.name }}
      - name: Use own Action
        uses: RickardHF/javascript-action@main
  prod:
    environment: Production
    needs: [staging]
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo ${{ github.event.inputs.name }}
      - name: Use own Action
        uses: RickardHF/javascript-action@main
